version: "3.6"

x-deploy:
  &default-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s

# ============================================================================ #

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/volumes:/var/lib/docker/volumes
    networks:
      portainer_agent:
        aliases:
          - agent
    ports:
        - "9001:9001"
    deploy:
      << : *default-deploy
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    networks:
      portainer_agent:
        aliases:
          - portainer
    command: -H "tcp://tasks.agent:9001" --tlsskipverify
    volumes:
      - portainer_data:/data
    deploy:
      << : *default-deploy
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
    depends_on:
      - agent
          
volumes:
  portainer_data:

networks:
  portainer_agent:
    driver: overlay
    attachable: true                                                        
