version: "3.6"

x-deploy:
  &default-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s

# ============================================================================ #

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/volumes:/var/lib/docker/volumes
    networks:
      portainer_agent:
        aliases:
          - agent
    ports:
        - "9001:9001"
    deploy:
      << : *default-deploy
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  portainer_agent:
    driver: overlay
    attachable: true                                                        
